### ISSUE TITLE
Y-Axis Ticks Property Issue

### ISSUE THREAD

**Issue by tensed** [cerner/carbon-graphs#235] opened 2020-06-12 07:03 UTC
**Describe the bug**
We were using Carbon Graph@2.4.0 where the y-axis ticks alignment issue was persisting! We had a workaround which used the rangeRounding and padDomain when set to true for both y1 and y2 axis, the ticks were aligned.
Due to the recent fix in Carbon Graph@2.5.1, it seems to be breaking and wasn't aligning.
Giving the tickCount worked but the ticks property seems to be broken as im unable to get the values when given on the axises.

**Link to CodeSandbox**

[Sandbox](https://codesandbox.io/s/jovial-montalcini-s1ykp?file=/src/data.js ) 

**Expected behavior**
*Ideally the tick values on the y-axes should be displayed as in* (This was in 2.4.0) 
<img width="1178" alt="Screenshot 2020-06-12 at 12 30 52 PM" src="https://user-images.githubusercontent.com/41514402/84474553-a9b64780-aca8-11ea-9c24-74eec2929d53.png">

But currently its displaying as 
<img width="1153" alt="Screenshot 2020-06-12 at 12 30 35 PM" src="https://user-images.githubusercontent.com/41514402/84474578-b2a71900-aca8-11ea-8058-6f25a2a2f0cb.png">

**Desktop (please complete the following information):**

-   OS: MacOS Mojave
-   Browser : Chrome, Firefox

**Comment by Veera81** [comment] 2020-06-12 14:21
@tensed Thanks for the logging the issue. @sdadn will be looking into the issue. We will update you based on our investigation.

For now, workaround, you can keep the `2.5.0` version in the package.json

**Comment by sdadn** [comment] 2020-06-12 17:23
@tensed can you try using a ticksCount value of 7? The ticksCount property should be in the top level of the GRAPH_DATA object.

**Comment by Veera81** [comment] 2020-06-12 19:40
Probably if use the `ticksCount` to 7 and remove the values will fix the issue

![image](https://user-images.githubusercontent.com/62761486/84540238-88f6ed80-acba-11ea-979e-a9db9392d8fd.png)

@sdadn Did `ticksCount` property is optional or mandatory?

**Comment by sdadn** [comment] 2020-06-12 19:47
`ticksCount` is optional; if not provided then the number of ticks will be based on the Y and Y2 ranges.

**Comment by Veera81** [comment] 2020-06-12 20:01
The consumer provided the Y and Y2 ranges I guess. Did you investigate why it was not creating all ticks?

**Comment by sdadn** [comment] 2020-06-12 20:18
I believe the updated behavior to automatically calculate ticks overrides the case when custom tick values are given. I am currently reviewing the design of the solution.

**Comment by mraplumb** [comment] 2020-06-12 21:34
@sdadn We should definitely look to reverse that.  If the consumer provides a custom array of ticks, they should continue to be utilized and the automatic calculation of ticks based on the axis range should be bypassed and the optional tickCount property ignored even if provided.

**Comment by tensed** [comment] 2020-06-15 05:00
@Veera81 @sdadn Thank you for your inputs! I did try checking with the ticksCount option and the numbering seems to be back, but when values are charted, its not on the tick lines. (the spacing between them seems to not align with the numbers on the axises. Tried tinkering around the allowCallibration as well but it didn't seem to work.
I'll be reverting back to 2.5.0 until then. 
<img width="1114" alt="sandbox" src="https://user-images.githubusercontent.com/41514402/84619587-2a688400-aef3-11ea-99c1-79260ea16dbf.png">

**Comment by JananiGunasekaran** [comment] 2020-06-16 15:57
@Veera81 @mraplumb @sdadn Due to the recent fix in Carbon Graph@2.5.1, we are facing an issue which causes an extra horizontal line to display after the canvas.
 
Link to Sandbox:
[Sandbox](https://codesandbox.io/s/nice-feynman-kwdo6?file=/src/data.js)

This new line appears only for certain values of y-axis upperlimit and lowerlimit. Looks like if we give only values in the tens range like 10,20,30 etc, the line doesn't appear. The limits mentioned in the above sandbox are 35 and 110 and the line appears. But when we change it to 30 and 110, the line is no longer showing up. 

I have noticed that when we give 31 and 110, we are able to see the line just below the canvas bottom & when we give 39 and 110, we are able to see the line after some gap from the canvas bottom.

**Comment by sdadn** [comment] 2020-06-16 19:57
@JananiGunasekaran Thanks for your input, I'll investigate the cause behind that issue.

**Comment by JananiGunasekaran** [comment] 2020-06-17 05:48
> @JananiGunasekaran Thanks for your input, I'll investigate the cause behind that issue.

@sdadn Thank you. Also this issue happens only when allowCalibration is set to false.

**Comment by sdadn** [comment] 2020-06-22 20:27
@JananiGunasekaran I pushed a fix to the `issue235` branch. Can you take a look to see if the problem persists?

**Comment by JananiGunasekaran** [comment] 2020-06-23 10:43
> @JananiGunasekaran I pushed a fix to the `issue235` branch. Can you test that branch to see if the problem persists?

@sdadn I consumed the mentioned branch and tested. The extra horizontal line no longer appears after the canvas when allowCalibration is set to false.

But when i give limit values from 31 to 39, I see that the last tick value alone doesn't show up on the canvas. I mean after 40, the next tick value 30 is not showing up on the canvas.
I gave 35 and 110 as limits here.
![image](https://user-images.githubusercontent.com/60426528/85391471-dbac9100-b567-11ea-8250-8f5d30bb8097.png)

When i give limit values in the tens range like 10, 20, 30, the last tick value shows up on the canvas: 
I gave 30 and 110 as limits here.
![image](https://user-images.githubusercontent.com/60426528/85392739-99844f00-b569-11ea-978a-8a468b205aae.png)

Also I noticed that the last grid line within the canvas appears very close to the last line of the canvas when we give limit as 39 and 110:
![image](https://user-images.githubusercontent.com/60426528/85393874-57f4a380-b56b-11ea-9b34-2ca5b21865e1.png)

The last grid line actually moves either towards or away from the last line of the canvas when we keep changing the range from 31 to 39. 
31 will make the last grid line appear farther and 39 makes the last grid line appear closer to the canvas line.

**Comment by sdadn** [comment] 2020-06-23 15:48
@JananiGunasekaran Thanks Janani. So, when you don’t pass in ticksCount or tick values for a single Y axis, then the algorithm uses the original logic (pre-2.5.0) to automatically generate Y axis ticks. D3.js likes to round off numbers to multiples of 2, 5 or 10 to have cleaner values.

The unmarked tick is the value between the multiples, but still in scale. Which is why 31 appears further down than 39. If `allowCallibration` is set to _true_, then the lower limit would be updated to 30 to accommodate 31 or 39.  With `allowCalibration` set to _false_, the upper and lower limits don’t update and the lower/upper limits stay the same. If the limit is not a multiple, then they are not labelled.

The original logic was intentionally left in place so a consumer can use a graph with minimal configuration and have clean axis values. You can pass in different limits, use custom tick values or ticksCount to get around this. We can look at enhancing the default behavior in the future, but it is not a bug within the context of this issue.

**Comment by JananiGunasekaran** [comment] 2020-06-24 05:53
@sdadn Thanks for the clarification!

**Closed** 2020-07-08 13:48 UTC
Labels: bug
