### ISSUE TITLE
Line graph Y-axes icon animation

### ISSUE THREAD

**Issue by tensed** [cerner/carbon-graphs#320] opened 2020-11-25 04:53 UTC
**What part of Carbon does this feature request correlate to?**

General graph logic:

* [X]  Graph attributes (axes, legends, regions...etc.)
* [ ]  Other (please specify): 

Specific graph logic:

* [ ]  Bar graph
* [ ]  Bubble graph
* [ ]  Gantt chart
* [X]  Line graph
* [ ]  Paired result
* [ ]  Pie chart
* [ ]  Scatter plot
* [ ]  Timeline

**Is your feature request related to a problem? Please describe.**
When we try to load any line graph components which has both y1 and y2 axis, the icons on the y1-axis and y2-axis seems to come sliding from top of the graph as though it is animated. When we try to load two or more datasets, and in case if the loading of the graph is really slow, the icons seems to glitch out on top for a while and then goes to their respective axes. 

**Describe the solution you'd like**
Could there be an option for disabling the animation for the y-axes icons or would it be possible to 

**Describe alternatives you've considered**
Had tried to use css animation properties as well as making it visible only when the graph is rendered completely but to no use as it does not seem to reflect the css changes at all. 
Tried disabling the showShape property as well but then it completely went off.

**Additional context**
In case if the bandwidth is really slow we can notice the icons glitching out on top and then coming to the y-axes.
To recreate this, we can use developer tools and use the device toolbar.
In case of chrome - you can set the network to low tier mobile 
In case of firefox - Good 3g should do the trick.

Attaching pictures:-
<img width="931" alt="Screenshot 2020-11-24 at 7 46 43 PM" src="https://user-images.githubusercontent.com/41514402/100184771-3f1c5f80-2f08-11eb-9db9-5989136fc2bb.png">

**Comment by sdadn** [comment] 2020-12-09 16:24
Hi @tensed . Can you provide a sandbox that replicates the graph in the figure shown? And does this issue consistently occur, or does it happen sporadically?

**Comment by tensed** [comment] 2020-12-11 05:34
SandBox - https://codesandbox.io/s/agitated-river-nech7?file=/src/data.js 

I've tried to replicate it as much as possible but it seems like since the sandbox gets loaded offline, it loads up instantly without the animation if we put the network settings to low. Tried opening the sandbox on IE but it didn't open at all. 

<img width="1440" alt="Screenshot 2020-12-11 at 10 25 21 AM" src="https://user-images.githubusercontent.com/41514402/101867114-6d549d00-3ba0-11eb-8f49-cccdffdcea04.png">


It seems to occur when there is a lot of data + padDomain and rangeRounding which realigns the graph ticks and ends up glitching out.
I'll see if I can recreate the same as shown in the picture that I've attached!

**Comment by mraplumb** [comment] 2020-12-22 22:33
@tensed we are having a lot of difficulty recreating the shapes not moving down to their axes.  Can you provide more details around the environment that you are seeing this in?  You mentioned emulating the network speed to a slower speed like 3G but all of the animation happens on the client side browser so it is unlikely that the network speed would affect this unless you have numerous data requests going out and being processed at the same time that the browser is trying to construct the graphs.

Can you provide more context such as, but not limited to the following items:

- What type of device is this being seen on (brand, model, connection type...etc.)
- How many Carbon graphs are being rendered on the page in question?
- What other content is being rendered on the DOM in addition to the graphs created using Carbon?

We want to be able to recreate this, somewhat reliably, before making any changes so that we can test to ensure the changes have the intended effect and do not negatively impact other areas.

**Comment by tensed** [comment] 2020-12-29 11:17
The shapes do eventually move down to their axes! As you had mentioned, it does not really seem to occur while using mock data but maybe with the service requests it might tend to slow down.  
Here are the details as requested:
**Device used** :- Macbook Pro 15" 2019 
**Browsers that have been tested on**: IE11, Firefox and Chrome
There are two graphs which are being rendered:
- **Line graph** which has about 3 types of data that are being loaded into the graph for creating the graph 
- **Gantt chart** which has custom svgs. 

Legends are rendered for each of those graphs as well as we're using stella timeline for the same.
Please let me know if you need any more further information! 

Thanks!

**Comment by mjhenkes** [comment] 2021-01-08 16:45
Duplicate of terra-graphs issue https://github.com/cerner/terra-graphs/issues/33

**Closed by mjhenkes** 2021-01-08 16:45 UTC
Labels: :construction: blocked: engineering input needed, assessing issue
