### ISSUE TITLE
Align padding between timeline and graph

### ISSUE THREAD

**Issue by jeffmerten** [cerner/carbon-graphs#104] opened 2019-10-17 15:30 UTC
**Is your feature request related to a problem? Please describe.**
Our visualization for labs recently was affected by https://github.com/cerner/carbon-graphs/commit/b1584e2d45c301536d34176e7573466b4b82d13c. Previously our graph-timeline combo looked like this:
![Timeline graph combo](https://user-images.githubusercontent.com/34603098/67023735-8529b180-f0c0-11e9-9854-fe3c38fddd64.png)
After the commit above was released, it looked like this:
![Timeline graph combo broken](https://user-images.githubusercontent.com/34603098/67023718-7f33d080-f0c0-11e9-936b-19b461499a83.png)

**Describe the solution you'd like**
We'd like to be able to remove our custom padding and have the axes still be in alignment with one another. 

**Describe alternatives you've considered**
We might decide on locking carbon-graphs in our module to minor versions to prevent these issues going forward. Long term we'd like to avoid doing this.

**Additional context**

Here are the current custom paddings we apply when the timeline and graph are shown together:

```
timelinePadding = {
	top: 3,
	bottom: 5,
	left: 50,
	right: 50,
};
graphPadding = {
	top: 0,
	bottom: 5,
	left: 25,
	right: 67,
};
```
When the custom padding is not applied, the timeline graph looks like this:
<img width="857" alt="default padding" src="https://user-images.githubusercontent.com/34603098/67023691-72af7800-f0c0-11e9-9c29-1dfbc1de54bf.png">

**Comment by pranav300** [comment] 2019-10-18 09:54
I don't think the possible solution provided in the issue description can be done as they originate from different constructs and `Timeline` does not have Y label whereas, graph constructs require space for the label as well. What do you think? @abhijit945 


@jeffmerten In my opinion the possible solution you can go with is

```diff
timelinePadding = {
        top: 3,
        bottom: 5,
-        left: 50,
+        left: 100,
        right: 50,
      };
```

Reason:
If you see the code at line [718](https://github.com/cerner/carbon-graphs/blob/master/src/main/js/helpers/axis.js#L718), we have added `config.padding.left` to consider the spacing between y axes labels and axes for the graph construct. So for this reason timeline construct requires double the padding of graph construct. And in your test file, you are not displaying the label otherwise, you would also be required to consider `LabelWidth` while providing padding.

**Comment by abhijit945** [comment] 2019-10-18 11:59
+1

**Comment by jeffmerten** [comment] 2019-10-18 15:23
@pranav300 I agree it might not make sense to hold the padding the same between the time and graph due to the y axis difference. Is it safe for us to assume that timeline padding = 2 * graph padding going forward?

**Comment by pranav300** [comment] 2019-10-18 19:07
@jeffmerten I may not be able to guarantee about `timeline padding = 2 * graph padding` as label width should also be considered. But currently, as much as I know there is no enhancement that would change it. But again I can't guarantee about future enhancements.

**Comment by jeffmerten** [comment] 2019-10-18 19:42
Can the label width be exported for us to use?

**Comment by abhijit945** [comment] 2019-10-21 12:58
The padding property is always going to be `content padding` i.e. padding relative to the content. 

![image](https://user-images.githubusercontent.com/4908886/67206599-9da70e00-f3d7-11e9-9864-af885d8eb672.png)

If you want a graph level padding then I think solely depending on the above property to position your timeline is not desirable in your scenario. For your scenario, wouldn't it be a better if we applied CSS-style padding (px. rem etc.) on the container instead i.e. Graph level padding?

**Comment by jeffmerten** [comment] 2019-10-21 14:17
I think that probably would be a better way, but if we apply that css style padding on our own container we still have the same problem: how do we ensure alignment is maintained in our module in the future without locking carbon-graphs to a specific version?

**Comment by abhijit945** [comment] 2019-10-21 14:39
Good point. 
The issue is that Carbon has a default padding property for content and we have exposed it to consumers to be modified. 
In this case, the consumer is entirely responsible for managing the padding left and right. Carbon sets out with initial setting of having no padding or margin. 

**Proposal**
It goes without saying that this has not been implemented; padding and margin are not accounted for when the [width](https://github.com/cerner/carbon-graphs/blob/master/src/main/js/controls/Graph/Graph.js#L53) of the container is calculated. This however can be done by doing something like [this](https://github.com/cerner/carbon-graphs/blob/4288c90e473809c745dbabe8a9b93b40d1bb3ff2/src/main/js/helpers/padding.js#L20). When consumer doesnt provide the padding and/margin, the width will take 100% of the container.

**Comment by abhijit945** [comment] 2019-12-03 20:52
@jeffmerten Created https://github.com/cerner/carbon-graphs/issues/121
Is what you were looking for?

**Comment by abhijit945** [comment] 2019-12-19 17:52
I think this will be fixed with above issue, please feel free to reopen this if you have additional concerns.

**Closed by abhijit945** 2019-12-19 17:52 UTC
