### ISSUE TITLE
Graph does not resize inside a modal unless resolution is changes

### ISSUE THREAD

**Issue by hackawesome** [cerner/carbon-graphs#239] opened 2020-06-15 15:36 UTC
**Describe the bug**
I have loaded a graph & table in a modal dialog using Terra-Disclosure-Manager & Terra-Modal-Manager. One click of the max button on the header, the dialog expands but the graph does not resize. Once I try to change the resolution or windows size, graph size updates. 
Similarly if I minimize the dialog, the graph does not dynamically loads & comes to a proper size once the resolution or window size.

**Link to CodeSandbox**
Link to reproduce the issue:
Branch: https://github.cerner.com/aeon-womenshealth/overview-component-js/tree/BLRWH-8065-merge
Disclosed from header file: https://github.cerner.com/aeon-womenshealth/overview-component-js/blob/be9b85f4b06b94e5dc1a45be1dda73d60118cc85/src/overview-component/components/OverviewHeader.jsx#L66 

**Expected behavior**
Once the maximize button is clicked, graph should automatically resize & vice versa with the minimize button.

**Screenshots**
Video: https://cernerprod-my.sharepoint.com/:v:/g/personal/hs067805_cerner_net/EbSiqkeAYBlJgrwDsOKOgZoBGr_0_3S_e5pkDQd5ZzHAUg?e=cMzHqt

**Comment by sdadn** [comment] 2020-08-26 17:50
Duplicate of #163 .

**Closed** 2020-08-26 17:51 UTC
Labels: duplicate
