### ISSUE TITLE
Gantt does not unload content properly

### ISSUE THREAD

**Issue by Matthematic** [cerner/carbon-graphs#256] opened 2020-07-06 15:43 UTC
**Describe the bug**
While upgrading to carbon 2.x.x I have discovered a bug with the Gantt chart where unloading tracks can mess something up, and content from one track will then bleed into another. Resizing the window fixes it, so whatever the bug is must be isolated to the unloadContent. This was not a problem on 1.x.x versions, which you can see by changing the version in the codesandbox below.

**Link to CodeSandbox**

https://codesandbox.io/s/goofy-blackwell-vgzh9?file=/src/graph.js

**Expected behavior**
The track(s) are unloaded without any bleeding or merging of other tracks

**Screenshots**
![image](https://user-images.githubusercontent.com/6292111/86612135-46e96080-bf75-11ea-82d0-6afe2dba1a07.png)

**Desktop (please complete the following information):**

-   OS: windows, ubuntu
-   Browser: chrome

**Comment by AshishMotanamGurunadham** [comment] 2020-07-06 15:47
@Matthematic Sorry for the inconvenience caused. Currently we are working on it and will get back to you once we are done with fixing the issue.

**Comment by mraplumb** [comment] 2020-07-09 22:36
Duplicate of #245

**Closed by mraplumb** 2020-07-09 22:36 UTC
Labels: duplicate
