### ISSUE TITLE
Y - axis intervals are not coming as expected when no data loads in the graph 

### ISSUE THREAD

**Issue by avinashrock** [cerner/carbon-graphs#124] opened 2019-12-12 07:42 UTC
**Describe the bug**
If there is no data loaded in the graph the y axis intervals start from 60 and end at 190 , even when the tick values are specified from 60 till 210. the lower limit is 90 and the upperlimit is 190
ticks: {
          values: [60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210],
        }

**To Reproduce**

In the graph input json give the y as

y: {
label: 'y-axis',
lowerLimit: 90,
upperLimit: 190,
ticks: {
values: [60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210],
},
},

**Expected behavior**
The y-axis ticks should start from 60 and go till 210.  as the lower, upper limit and the ticks provided.( division should be as per the ticks are given in the values array)

**Screenshots**
![image](https://user-images.githubusercontent.com/9162342/70691962-61f63980-1ce0-11ea-9f5d-d3a00e169223.png)

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]
-   Browser [e.g. chrome, safari]

**Additional context**
#116

**Comment by abhijit945** [comment] 2019-12-20 16:03
I think its a bug that the 60 should be 90 rather. 
![image](https://user-images.githubusercontent.com/4908886/71267238-be281180-230f-11ea-9319-f2f1de443bad.png)

But other than that, I think its working as intended. The ticks -> values are supposed to be **within** the limits. The axis values are re-adjusted only when the content values are an outlier.

**Comment by abhijit945** [comment] 2019-12-27 14:26
Closing this issue since its working as intended. Feel free to reopen if you feel otherwise.

**Closed by abhijit945** 2019-12-27 14:26 UTC
