### ISSUE TITLE
Truncation of Label Pop-Up

### ISSUE THREAD

**Issue by abhijit945** [cerner/carbon-graphs#6] opened 2019-07-10 21:06 UTC
Change the labels to only show the pop-up with the full text if the label has been truncated. 

Show full-text pop-up when text is >12 characters. Do not show when <12 characters.

**Comment by AshishMotanamGurunadham** [comment] 2020-08-24 17:55
Duplicate of issue #208 and resolved with PR #242

**Closed by AshishMotanamGurunadham** 2020-08-24 17:55 UTC
Labels: duplicate, enhancement, good first issue, help wanted
