### ISSUE TITLE
Ability to associate event to a bar / icon selection 

### ISSUE THREAD

**Issue by laurunning** [cerner/carbon-graphs#100] opened 2019-10-15 20:01 UTC
The ability to associate an event to a bar would allow for better selection of an icon and bar below it. Also, the selection of an icon is not large enough to encompass the full view: 
![image](https://user-images.githubusercontent.com/32143728/66865288-8b068200-ef5c-11e9-883a-26b2edc5ddc2.png)

Proposal to make the selection either wrap the icon or make it a rectangle like the one for chunks.

**Comment by laurunning** [comment] 2019-10-18 19:51
Can it use the same logic for selection as the bars do? So it grows to match the width of the icon like it would match the width of a bar?

**Comment by laurenbock** [comment] 2019-11-26 21:13
Yes - enhancement, doable, follow rectangular pattern as in bars.

**Comment by laurenbock** [comment] 2019-11-26 21:23
This is a duplicate of this issue: https://github.com/cerner/carbon-graphs/issues/5

**Closed** 2019-11-26 21:23 UTC
Labels: duplicate
